version: '3.9'

services:
  nginx:
    image: dock/nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8090:80"
    networks:
      - nginx-network
    depends_on:
      - app
  app:
    image: dock/bank-account-service:latest
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DB_USERNAME=bank-account
      - DB_PASSWORD=bank-account
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=bank-account-db
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s java -jar /app.jar
    expose:
      - "8080"
    networks:
      - mysql-network
      - nginx-network
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=bank-account-db
      - MYSQL_USER=bank-account
      - MYSQL_PASSWORD=bank-account
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
  nginx-network:
    driver: bridge