version: '3.9'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bank-account-db
      - MYSQL_USER=module
      - MYSQL_PASSWORD=module
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - database-network
  application:
    image: dock/bank-account-service:latest
    build:
      context: .
      dockerfile: Dockerfile.application
    environment:
      - DB_USERNAME=bank-account
      - DB_PASSWORD=bank-account
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=bank-account-db
    entrypoint: dockerize -wait tcp://mysql:3306 java -jar /app.jar
    networks:
      - database-network
      - proxy-network
    depends_on:
      - mysql
  reverse-proxy:
    image: dock/web-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 8000:80
    entrypoint: dockerize -wait http://application:8080 /docker-entrypoint.sh nginx -g daemon
    depends_on:
      - application
    networks:
      - proxy-network

networks:
  database-network:
    driver: bridge
  proxy-network:
    driver: bridge